[package]
name = "user_lib"
version = "0.1.0"
edition = "2024"

[dependencies]
riscv = { git = "ssh://git@github.com/rcore-os/riscv.git", features = ["inline-asm"] } 

[profile.release]
debug = true
opt-level = 0               # 优化级别,最低是0,最高是3, 0方便debug
overflow-checks = false     # 关闭整数溢出检查